ExpenseTracker/Controllers/ExpensesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExpenseTracker.Models;

namespace ExpenseTracker.Controllers
{
    public class ExpensesController : Controller
    {
        private readonly ExpensesContext _context;

        public ExpensesController(ExpensesContext context)
        {
            _context = context;
        }

        // GET: Expenses
        public async Task<IActionResult> Index()
        {
            var expensesContext = _context.Expenses.Include(e => e.ExpenseCategory);
            return View(await expensesContext.ToListAsync());
        }

        // GET: Expenses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expense = await _context.Expenses
                .Include(e => e.ExpenseCategory)
                .FirstOrDefaultAsync(m => m.ExpensesId == id);
            if (expense == null)
            {
                return NotFound();
            }

            return View(expense);
        }

        // GET: Expenses/Create
        public IActionResult Create()
        {
            ViewData["ExpenseCategoryId"] = new SelectList(_context.ExpenseCategorys, "CategoryId", "CategoryName");
            return View();
        }

        // POST: Expenses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ExpensesId,ExpensesName,DateOfExpense,ExpenseAmount,ExpenseCategoryId")] Expense expense)
        {
            if (ModelState.IsValid)
            {
                if (expense.DateOfExpense.Date>DateTime.Now.Date)
                {
                    TempData["ErrorMes"] =" Expence Date invalid.";
                    return RedirectToAction(nameof(Create));
                }
                _context.Add(expense);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ExpenseCategoryId"] = new SelectList(_context.ExpenseCategorys, "CategoryId", "CategoryId", expense.ExpenseCategoryId);
            return View(expense);
        }

        // GET: Expenses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expense = await _context.Expenses.FindAsync(id);
            if (expense == null)
            {
                return NotFound();
            }
            ViewData["ExpenseCategoryId"] = new SelectList(_context.ExpenseCategorys, "CategoryId", "CategoryName", expense.ExpenseCategoryId);
            return View(expense);
        }

        // POST: Expenses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ExpensesId,ExpensesName,DateOfExpense,ExpenseAmount,ExpenseCategoryId")] Expense expense)
        {
            if (id != expense.ExpensesId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (expense.DateOfExpense.Date > DateTime.Now.Date)
                    {
                        TempData["ErrorMes"] = " Expence Date invalid.";
                        return RedirectToAction(nameof(Edit));
                    }
                    _context.Update(expense);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExpenseExists(expense.ExpensesId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ExpenseCategoryId"] = new SelectList(_context.ExpenseCategorys, "CategoryId", "CategoryId", expense.ExpenseCategoryId);
            return View(expense);
        }

        // GET: Expenses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expense = await _context.Expenses
                .Include(e => e.ExpenseCategory)
                .FirstOrDefaultAsync(m => m.ExpensesId == id);
            if (expense == null)
            {
                return NotFound();
            }

            return View(expense);
        }

        // POST: Expenses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var expense = await _context.Expenses.FindAsync(id);
            _context.Expenses.Remove(expense);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ExpenseExists(int id)
        {
            return _context.Expenses.Any(e => e.ExpensesId == id);
        }

        public IActionResult Report()
        {            
            return View();
        }

        // POST: Expenses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Report(DateTime fromDate,DateTime toDate)
        {
            var exp =  _context.Expenses.Include(e => e.ExpenseCategory).Where(e=>e.DateOfExpense >= fromDate && e.DateOfExpense <= toDate);

            return View(exp);
        }
    }
}

ExpenseTracker/Views/Expenses/Create.cshtml
@model ExpenseTracker.Models.Expense

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Expense</h4>
<hr />
<span class="text-danger">@TempData["ErrorMes"]</span>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ExpensesName" class="control-label"></label>
                <input asp-for="ExpensesName" class="form-control" />
                <span asp-validation-for="ExpensesName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfExpense" class="control-label"></label>
                <input asp-for="DateOfExpense" type="date" class="form-control" />
                <span asp-validation-for="DateOfExpense" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpenseAmount" class="control-label"></label>
                <input asp-for="ExpenseAmount" class="form-control" />
                <span asp-validation-for="ExpenseAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpenseCategoryId" class="control-label"></label>
                <select asp-for="ExpenseCategoryId" class ="form-control" asp-items="ViewBag.ExpenseCategoryId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExpenseTracker/Views/Expenses/Delete.cshtml
@model ExpenseTracker.Models.Expense

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Expense</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpensesName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpensesName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfExpense)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfExpense)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpenseAmount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpenseAmount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpenseCategory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpenseCategory.CategoryId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ExpensesId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ExpenseTracker/Views/Expenses/Details.cshtml
@model ExpenseTracker.Models.Expense

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Expense</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpensesName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpensesName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfExpense)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfExpense)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpenseAmount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpenseAmount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpenseCategory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpenseCategory.CategoryId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ExpensesId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ExpenseTracker/Views/Expenses/Edit.cshtml
@model ExpenseTracker.Models.Expense

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Expense</h4>
<hr />
<span class="text-danger">@TempData["ErrorMes"]</span>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ExpensesId" />
            <div class="form-group">
                <label asp-for="ExpensesName" class="control-label"></label>
                <input asp-for="ExpensesName" class="form-control" />
                <span asp-validation-for="ExpensesName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfExpense" class="control-label"></label>
                <input asp-for="DateOfExpense" type="date" class="form-control" />
                <span asp-validation-for="DateOfExpense" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpenseAmount" class="control-label"></label>
                <input asp-for="ExpenseAmount" class="form-control" />
                <span asp-validation-for="ExpenseAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpenseCategoryId" class="control-label"></label>
                <select asp-for="ExpenseCategoryId" class="form-control" asp-items="ViewBag.ExpenseCategoryId"></select>
                <span asp-validation-for="ExpenseCategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExpenseTracker/Views/Expenses/Index.cshtml
@model IEnumerable<ExpenseTracker.Models.Expense>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ExpensesName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfExpense)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpenseAmount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpenseCategory.CategoryName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ExpensesName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfExpense)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpenseAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpenseCategory.CategoryName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ExpensesId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ExpensesId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ExpensesId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

ExpenseTracker/Views/Expenses/Report.cshtml
@model IEnumerable<ExpenseTracker.Models.Expense>

@{
    ViewData["Title"] = "Index";
}

<h1>Report</h1>

<form asp-action="Report" asp-controller="Expenses" method="post">
    <div class="row">
        <div class="col-md-2">
            <span>From Date</span>
        </div>
        <div class="col-md-4">
            <input name="fromDate" type="date" class="form-control" />
        </div>
        <div class="col-md-2">
            <span>To Date</span>
        </div>
        <div class="col-md-4">
            <input name="toDate" type="date" class="form-control" />
        </div>
    </div>
    <div class="row" style="padding-top:10px">
        <div class="col-md-12" style="align-content:center">
            <input name="submit" type="submit" value="Filter" class="form-control" />
        </div>
    </div>
</form>


@if (Model != null)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ExpensesName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DateOfExpense)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ExpenseAmount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ExpenseCategory.CategoryName)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ExpensesName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateOfExpense)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ExpenseAmount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ExpenseCategory.CategoryName)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.ExpensesId">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.ExpensesId">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.ExpensesId">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}